### PR TITLE
6674 custom apt sources

### PR DESCRIPTION
**Pull request by varac**
https://leap.se/code/issues/6674

### CODE REVIEW

**Comment by micah** [comment]
+1 from me, this looks good

**Comment by elijh** [comment]
in the future, i would like to create a sources.json file that allows you to put all the apt and git and gem and pypi urls in one place.

**Comment by varac** [comment]
@elijh  good idea ! is there an issue for this ?

**Comment by elijh** [comment]
https://leap.se/code/issues/6312

**Pull request merged**
